# Generated by Django 5.1.2 on 2024-10-30 14:17

import django.db.models.deletion
import mptt.fields
import versatileimagefield.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100, null=True, verbose_name='სახელი')),
                ('slug', models.SlugField(blank=True, default='')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='store.category', verbose_name='ზეკატეგორია')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100, verbose_name='სახელი')),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='ფასი')),
                ('product_description', models.TextField(blank=True, null=True, verbose_name='აღწერა')),
                ('product_rating', models.IntegerField(blank=True, null=True, verbose_name='შეფასება')),
                ('product_image', versatileimagefield.fields.VersatileImageField(blank=True, help_text='ატვირთეთ ფოტოსურათი', null=True, upload_to='', verbose_name='სურათი')),
                ('product_quantity', models.IntegerField(blank=True, null=True, verbose_name='მარაგშია:')),
                ('country', models.CharField(default='Agro Farm', max_length=150, verbose_name='country')),
                ('weight', models.PositiveIntegerField(default=1, verbose_name='წონა')),
                ('slug', models.SlugField(blank=True, default='', unique=True)),
                ('product_category', models.ManyToManyField(to='store.category', verbose_name='კატეგორია')),
                ('tags', models.ManyToManyField(blank=True, to='store.producttags')),
            ],
        ),
        migrations.CreateModel(
            name='ProductReviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('review', models.TextField(verbose_name='რევიუ')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product', verbose_name='პროდუქტი')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ავტორი')),
            ],
        ),
        migrations.CreateModel(
            name='ShopReviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField(verbose_name='რევიუ')),
                ('date', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ავტორი')),
            ],
        ),
    ]
