# Generated by Django 5.1.2 on 2024-10-30 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ქალაქი'),
        ),
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ქვეყანა'),
        ),
        migrations.AddField(
            model_name='user',
            name='mobile',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ტელეფონის ნომერი'),
        ),
        migrations.AddField(
            model_name='user',
            name='order_address',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='მისამართი'),
        ),
        migrations.AddField(
            model_name='user',
            name='postcode',
            field=models.IntegerField(blank=True, null=True, verbose_name='საფოსტო კოდი'),
        ),
    ]
