# Generated by Django 5.1.2 on 2024-10-30 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='last_name',
        ),
    ]
