# Generated by Django 5.1.2 on 2024-10-30 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_remove_checkout_first_name_remove_checkout_last_name'),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CartItems',
            new_name='CartItem',
        ),
    ]
