# Generated by Django 5.1.2 on 2024-10-30 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_rename_cartitems_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='city',
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='country',
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='email',
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='order_address',
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='postcode',
        ),
    ]
